// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: pkg/kvstore/interface/grpc/kvstore.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	KVStore_ForwardGet_FullMethodName     = "/kvstore.grpc.KVStore/ForwardGet"
	KVStore_ForwardPut_FullMethodName     = "/kvstore.grpc.KVStore/ForwardPut"
	KVStore_ForwardDelete_FullMethodName  = "/kvstore.grpc.KVStore/ForwardDelete"
	KVStore_ReplicateEntry_FullMethodName = "/kvstore.grpc.KVStore/ReplicateEntry"
	KVStore_Heartbeat_FullMethodName      = "/kvstore.grpc.KVStore/Heartbeat"
)

// KVStoreClient is the client API for KVStore service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ─────────────────────────────────────────────
// KVStore gRPC service
// ─────────────────────────────────────────────
type KVStoreClient interface {
	// Forwarding RPCs — used by a coordinator to forward client requests
	// to the node that owns the key.
	ForwardGet(ctx context.Context, in *ForwardGetRequest, opts ...grpc.CallOption) (*ForwardGetResponse, error)
	ForwardPut(ctx context.Context, in *ForwardPutRequest, opts ...grpc.CallOption) (*ForwardPutResponse, error)
	ForwardDelete(ctx context.Context, in *ForwardDeleteRequest, opts ...grpc.CallOption) (*ForwardDeleteResponse, error)
	// Replication — push a log entry from the leader to a replica.
	ReplicateEntry(ctx context.Context, in *ReplicateEntryRequest, opts ...grpc.CallOption) (*ReplicateEntryResponse, error)
	// Cluster health — lightweight liveness ping between nodes.
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
}

type kVStoreClient struct {
	cc grpc.ClientConnInterface
}

func NewKVStoreClient(cc grpc.ClientConnInterface) KVStoreClient {
	return &kVStoreClient{cc}
}

func (c *kVStoreClient) ForwardGet(ctx context.Context, in *ForwardGetRequest, opts ...grpc.CallOption) (*ForwardGetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ForwardGetResponse)
	err := c.cc.Invoke(ctx, KVStore_ForwardGet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kVStoreClient) ForwardPut(ctx context.Context, in *ForwardPutRequest, opts ...grpc.CallOption) (*ForwardPutResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ForwardPutResponse)
	err := c.cc.Invoke(ctx, KVStore_ForwardPut_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kVStoreClient) ForwardDelete(ctx context.Context, in *ForwardDeleteRequest, opts ...grpc.CallOption) (*ForwardDeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ForwardDeleteResponse)
	err := c.cc.Invoke(ctx, KVStore_ForwardDelete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kVStoreClient) ReplicateEntry(ctx context.Context, in *ReplicateEntryRequest, opts ...grpc.CallOption) (*ReplicateEntryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReplicateEntryResponse)
	err := c.cc.Invoke(ctx, KVStore_ReplicateEntry_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kVStoreClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, KVStore_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KVStoreServer is the server API for KVStore service.
// All implementations must embed UnimplementedKVStoreServer
// for forward compatibility.
//
// ─────────────────────────────────────────────
// KVStore gRPC service
// ─────────────────────────────────────────────
type KVStoreServer interface {
	// Forwarding RPCs — used by a coordinator to forward client requests
	// to the node that owns the key.
	ForwardGet(context.Context, *ForwardGetRequest) (*ForwardGetResponse, error)
	ForwardPut(context.Context, *ForwardPutRequest) (*ForwardPutResponse, error)
	ForwardDelete(context.Context, *ForwardDeleteRequest) (*ForwardDeleteResponse, error)
	// Replication — push a log entry from the leader to a replica.
	ReplicateEntry(context.Context, *ReplicateEntryRequest) (*ReplicateEntryResponse, error)
	// Cluster health — lightweight liveness ping between nodes.
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	mustEmbedUnimplementedKVStoreServer()
}

// UnimplementedKVStoreServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedKVStoreServer struct{}

func (UnimplementedKVStoreServer) ForwardGet(context.Context, *ForwardGetRequest) (*ForwardGetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ForwardGet not implemented")
}
func (UnimplementedKVStoreServer) ForwardPut(context.Context, *ForwardPutRequest) (*ForwardPutResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ForwardPut not implemented")
}
func (UnimplementedKVStoreServer) ForwardDelete(context.Context, *ForwardDeleteRequest) (*ForwardDeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ForwardDelete not implemented")
}
func (UnimplementedKVStoreServer) ReplicateEntry(context.Context, *ReplicateEntryRequest) (*ReplicateEntryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReplicateEntry not implemented")
}
func (UnimplementedKVStoreServer) Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedKVStoreServer) mustEmbedUnimplementedKVStoreServer() {}
func (UnimplementedKVStoreServer) testEmbeddedByValue()                 {}

// UnsafeKVStoreServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KVStoreServer will
// result in compilation errors.
type UnsafeKVStoreServer interface {
	mustEmbedUnimplementedKVStoreServer()
}

func RegisterKVStoreServer(s grpc.ServiceRegistrar, srv KVStoreServer) {
	// If the following call panics, it indicates UnimplementedKVStoreServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&KVStore_ServiceDesc, srv)
}

func _KVStore_ForwardGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForwardGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KVStoreServer).ForwardGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KVStore_ForwardGet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KVStoreServer).ForwardGet(ctx, req.(*ForwardGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KVStore_ForwardPut_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForwardPutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KVStoreServer).ForwardPut(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KVStore_ForwardPut_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KVStoreServer).ForwardPut(ctx, req.(*ForwardPutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KVStore_ForwardDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForwardDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KVStoreServer).ForwardDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KVStore_ForwardDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KVStoreServer).ForwardDelete(ctx, req.(*ForwardDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KVStore_ReplicateEntry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReplicateEntryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KVStoreServer).ReplicateEntry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KVStore_ReplicateEntry_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KVStoreServer).ReplicateEntry(ctx, req.(*ReplicateEntryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KVStore_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KVStoreServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KVStore_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KVStoreServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// KVStore_ServiceDesc is the grpc.ServiceDesc for KVStore service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KVStore_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kvstore.grpc.KVStore",
	HandlerType: (*KVStoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ForwardGet",
			Handler:    _KVStore_ForwardGet_Handler,
		},
		{
			MethodName: "ForwardPut",
			Handler:    _KVStore_ForwardPut_Handler,
		},
		{
			MethodName: "ForwardDelete",
			Handler:    _KVStore_ForwardDelete_Handler,
		},
		{
			MethodName: "ReplicateEntry",
			Handler:    _KVStore_ReplicateEntry_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _KVStore_Heartbeat_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/kvstore/interface/grpc/kvstore.proto",
}
