// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: pkg/kvstore/interface/grpc/kvstore.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ─────────────────────────────────────────────
// ForwardGet
// ─────────────────────────────────────────────
type ForwardGetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForwardGetRequest) Reset() {
	*x = ForwardGetRequest{}
	mi := &file_pkg_kvstore_interface_grpc_kvstore_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardGetRequest) ProtoMessage() {}

func (x *ForwardGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_kvstore_interface_grpc_kvstore_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardGetRequest.ProtoReflect.Descriptor instead.
func (*ForwardGetRequest) Descriptor() ([]byte, []int) {
	return file_pkg_kvstore_interface_grpc_kvstore_proto_rawDescGZIP(), []int{0}
}

func (x *ForwardGetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type ForwardGetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         []byte                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Found         bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForwardGetResponse) Reset() {
	*x = ForwardGetResponse{}
	mi := &file_pkg_kvstore_interface_grpc_kvstore_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardGetResponse) ProtoMessage() {}

func (x *ForwardGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_kvstore_interface_grpc_kvstore_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardGetResponse.ProtoReflect.Descriptor instead.
func (*ForwardGetResponse) Descriptor() ([]byte, []int) {
	return file_pkg_kvstore_interface_grpc_kvstore_proto_rawDescGZIP(), []int{1}
}

func (x *ForwardGetResponse) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *ForwardGetResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

// ─────────────────────────────────────────────
// ForwardPut
// ─────────────────────────────────────────────
type ForwardPutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForwardPutRequest) Reset() {
	*x = ForwardPutRequest{}
	mi := &file_pkg_kvstore_interface_grpc_kvstore_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardPutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardPutRequest) ProtoMessage() {}

func (x *ForwardPutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_kvstore_interface_grpc_kvstore_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardPutRequest.ProtoReflect.Descriptor instead.
func (*ForwardPutRequest) Descriptor() ([]byte, []int) {
	return file_pkg_kvstore_interface_grpc_kvstore_proto_rawDescGZIP(), []int{2}
}

func (x *ForwardPutRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ForwardPutRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type ForwardPutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForwardPutResponse) Reset() {
	*x = ForwardPutResponse{}
	mi := &file_pkg_kvstore_interface_grpc_kvstore_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardPutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardPutResponse) ProtoMessage() {}

func (x *ForwardPutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_kvstore_interface_grpc_kvstore_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardPutResponse.ProtoReflect.Descriptor instead.
func (*ForwardPutResponse) Descriptor() ([]byte, []int) {
	return file_pkg_kvstore_interface_grpc_kvstore_proto_rawDescGZIP(), []int{3}
}

func (x *ForwardPutResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// ─────────────────────────────────────────────
// ForwardDelete
// ─────────────────────────────────────────────
type ForwardDeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForwardDeleteRequest) Reset() {
	*x = ForwardDeleteRequest{}
	mi := &file_pkg_kvstore_interface_grpc_kvstore_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardDeleteRequest) ProtoMessage() {}

func (x *ForwardDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_kvstore_interface_grpc_kvstore_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardDeleteRequest.ProtoReflect.Descriptor instead.
func (*ForwardDeleteRequest) Descriptor() ([]byte, []int) {
	return file_pkg_kvstore_interface_grpc_kvstore_proto_rawDescGZIP(), []int{4}
}

func (x *ForwardDeleteRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type ForwardDeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForwardDeleteResponse) Reset() {
	*x = ForwardDeleteResponse{}
	mi := &file_pkg_kvstore_interface_grpc_kvstore_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardDeleteResponse) ProtoMessage() {}

func (x *ForwardDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_kvstore_interface_grpc_kvstore_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardDeleteResponse.ProtoReflect.Descriptor instead.
func (*ForwardDeleteResponse) Descriptor() ([]byte, []int) {
	return file_pkg_kvstore_interface_grpc_kvstore_proto_rawDescGZIP(), []int{5}
}

func (x *ForwardDeleteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// ─────────────────────────────────────────────
// ReplicateEntry
// ─────────────────────────────────────────────
type LogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SeqNum        uint64                 `protobuf:"varint,1,opt,name=seqNum,proto3" json:"seqNum,omitempty"`      // monotonically increasing log index
	Operation     string                 `protobuf:"bytes,2,opt,name=operation,proto3" json:"operation,omitempty"` // "PUT" | "DELETE"
	Key           string                 `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"` // empty for DELETE
	Term          string                 `protobuf:"bytes,5,opt,name=term,proto3" json:"term,omitempty"`   // leader term (useful for Raft-style consensus)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_pkg_kvstore_interface_grpc_kvstore_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_kvstore_interface_grpc_kvstore_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_pkg_kvstore_interface_grpc_kvstore_proto_rawDescGZIP(), []int{6}
}

func (x *LogEntry) GetSeqNum() uint64 {
	if x != nil {
		return x.SeqNum
	}
	return 0
}

func (x *LogEntry) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *LogEntry) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *LogEntry) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *LogEntry) GetTerm() string {
	if x != nil {
		return x.Term
	}
	return ""
}

type ReplicateEntryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entry         *LogEntry              `protobuf:"bytes,1,opt,name=entry,proto3" json:"entry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicateEntryRequest) Reset() {
	*x = ReplicateEntryRequest{}
	mi := &file_pkg_kvstore_interface_grpc_kvstore_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicateEntryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicateEntryRequest) ProtoMessage() {}

func (x *ReplicateEntryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_kvstore_interface_grpc_kvstore_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicateEntryRequest.ProtoReflect.Descriptor instead.
func (*ReplicateEntryRequest) Descriptor() ([]byte, []int) {
	return file_pkg_kvstore_interface_grpc_kvstore_proto_rawDescGZIP(), []int{7}
}

func (x *ReplicateEntryRequest) GetEntry() *LogEntry {
	if x != nil {
		return x.Entry
	}
	return nil
}

type ReplicateEntryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorDetail   string                 `protobuf:"bytes,2,opt,name=error_detail,json=errorDetail,proto3" json:"error_detail,omitempty"` // populated on failure
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicateEntryResponse) Reset() {
	*x = ReplicateEntryResponse{}
	mi := &file_pkg_kvstore_interface_grpc_kvstore_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicateEntryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicateEntryResponse) ProtoMessage() {}

func (x *ReplicateEntryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_kvstore_interface_grpc_kvstore_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicateEntryResponse.ProtoReflect.Descriptor instead.
func (*ReplicateEntryResponse) Descriptor() ([]byte, []int) {
	return file_pkg_kvstore_interface_grpc_kvstore_proto_rawDescGZIP(), []int{8}
}

func (x *ReplicateEntryResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReplicateEntryResponse) GetErrorDetail() string {
	if x != nil {
		return x.ErrorDetail
	}
	return ""
}

// ─────────────────────────────────────────────
// Heartbeat
// ─────────────────────────────────────────────
type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // Unix millis — lets the receiver detect clock skew
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_pkg_kvstore_interface_grpc_kvstore_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_kvstore_interface_grpc_kvstore_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_pkg_kvstore_interface_grpc_kvstore_proto_rawDescGZIP(), []int{9}
}

func (x *HeartbeatRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *HeartbeatRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"` // echo back so the sender can correlate replies
	Alive         bool                   `protobuf:"varint,2,opt,name=alive,proto3" json:"alive,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // Unix millis at response time
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_pkg_kvstore_interface_grpc_kvstore_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_kvstore_interface_grpc_kvstore_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_pkg_kvstore_interface_grpc_kvstore_proto_rawDescGZIP(), []int{10}
}

func (x *HeartbeatResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *HeartbeatResponse) GetAlive() bool {
	if x != nil {
		return x.Alive
	}
	return false
}

func (x *HeartbeatResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_pkg_kvstore_interface_grpc_kvstore_proto protoreflect.FileDescriptor

const file_pkg_kvstore_interface_grpc_kvstore_proto_rawDesc = "" +
	"\n" +
	"(pkg/kvstore/interface/grpc/kvstore.proto\x12\fkvstore.grpc\"%\n" +
	"\x11ForwardGetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"@\n" +
	"\x12ForwardGetResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\fR\x05value\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found\";\n" +
	"\x11ForwardPutRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\".\n" +
	"\x12ForwardPutResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"(\n" +
	"\x14ForwardDeleteRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"1\n" +
	"\x15ForwardDeleteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"|\n" +
	"\bLogEntry\x12\x16\n" +
	"\x06seqNum\x18\x01 \x01(\x04R\x06seqNum\x12\x1c\n" +
	"\toperation\x18\x02 \x01(\tR\toperation\x12\x10\n" +
	"\x03key\x18\x03 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x04 \x01(\fR\x05value\x12\x12\n" +
	"\x04term\x18\x05 \x01(\tR\x04term\"E\n" +
	"\x15ReplicateEntryRequest\x12,\n" +
	"\x05entry\x18\x01 \x01(\v2\x16.kvstore.grpc.LogEntryR\x05entry\"U\n" +
	"\x16ReplicateEntryResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12!\n" +
	"\ferror_detail\x18\x02 \x01(\tR\verrorDetail\"I\n" +
	"\x10HeartbeatRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\"`\n" +
	"\x11HeartbeatResponse\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x14\n" +
	"\x05alive\x18\x02 \x01(\bR\x05alive\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp2\xb0\x03\n" +
	"\aKVStore\x12O\n" +
	"\n" +
	"ForwardGet\x12\x1f.kvstore.grpc.ForwardGetRequest\x1a .kvstore.grpc.ForwardGetResponse\x12O\n" +
	"\n" +
	"ForwardPut\x12\x1f.kvstore.grpc.ForwardPutRequest\x1a .kvstore.grpc.ForwardPutResponse\x12X\n" +
	"\rForwardDelete\x12\".kvstore.grpc.ForwardDeleteRequest\x1a#.kvstore.grpc.ForwardDeleteResponse\x12[\n" +
	"\x0eReplicateEntry\x12#.kvstore.grpc.ReplicateEntryRequest\x1a$.kvstore.grpc.ReplicateEntryResponse\x12L\n" +
	"\tHeartbeat\x12\x1e.kvstore.grpc.HeartbeatRequest\x1a\x1f.kvstore.grpc.HeartbeatResponseB$Z\"kvstore/pkg/kvstore/interface/grpcb\x06proto3"

var (
	file_pkg_kvstore_interface_grpc_kvstore_proto_rawDescOnce sync.Once
	file_pkg_kvstore_interface_grpc_kvstore_proto_rawDescData []byte
)

func file_pkg_kvstore_interface_grpc_kvstore_proto_rawDescGZIP() []byte {
	file_pkg_kvstore_interface_grpc_kvstore_proto_rawDescOnce.Do(func() {
		file_pkg_kvstore_interface_grpc_kvstore_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_kvstore_interface_grpc_kvstore_proto_rawDesc), len(file_pkg_kvstore_interface_grpc_kvstore_proto_rawDesc)))
	})
	return file_pkg_kvstore_interface_grpc_kvstore_proto_rawDescData
}

var file_pkg_kvstore_interface_grpc_kvstore_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_pkg_kvstore_interface_grpc_kvstore_proto_goTypes = []any{
	(*ForwardGetRequest)(nil),      // 0: kvstore.grpc.ForwardGetRequest
	(*ForwardGetResponse)(nil),     // 1: kvstore.grpc.ForwardGetResponse
	(*ForwardPutRequest)(nil),      // 2: kvstore.grpc.ForwardPutRequest
	(*ForwardPutResponse)(nil),     // 3: kvstore.grpc.ForwardPutResponse
	(*ForwardDeleteRequest)(nil),   // 4: kvstore.grpc.ForwardDeleteRequest
	(*ForwardDeleteResponse)(nil),  // 5: kvstore.grpc.ForwardDeleteResponse
	(*LogEntry)(nil),               // 6: kvstore.grpc.LogEntry
	(*ReplicateEntryRequest)(nil),  // 7: kvstore.grpc.ReplicateEntryRequest
	(*ReplicateEntryResponse)(nil), // 8: kvstore.grpc.ReplicateEntryResponse
	(*HeartbeatRequest)(nil),       // 9: kvstore.grpc.HeartbeatRequest
	(*HeartbeatResponse)(nil),      // 10: kvstore.grpc.HeartbeatResponse
}
var file_pkg_kvstore_interface_grpc_kvstore_proto_depIdxs = []int32{
	6,  // 0: kvstore.grpc.ReplicateEntryRequest.entry:type_name -> kvstore.grpc.LogEntry
	0,  // 1: kvstore.grpc.KVStore.ForwardGet:input_type -> kvstore.grpc.ForwardGetRequest
	2,  // 2: kvstore.grpc.KVStore.ForwardPut:input_type -> kvstore.grpc.ForwardPutRequest
	4,  // 3: kvstore.grpc.KVStore.ForwardDelete:input_type -> kvstore.grpc.ForwardDeleteRequest
	7,  // 4: kvstore.grpc.KVStore.ReplicateEntry:input_type -> kvstore.grpc.ReplicateEntryRequest
	9,  // 5: kvstore.grpc.KVStore.Heartbeat:input_type -> kvstore.grpc.HeartbeatRequest
	1,  // 6: kvstore.grpc.KVStore.ForwardGet:output_type -> kvstore.grpc.ForwardGetResponse
	3,  // 7: kvstore.grpc.KVStore.ForwardPut:output_type -> kvstore.grpc.ForwardPutResponse
	5,  // 8: kvstore.grpc.KVStore.ForwardDelete:output_type -> kvstore.grpc.ForwardDeleteResponse
	8,  // 9: kvstore.grpc.KVStore.ReplicateEntry:output_type -> kvstore.grpc.ReplicateEntryResponse
	10, // 10: kvstore.grpc.KVStore.Heartbeat:output_type -> kvstore.grpc.HeartbeatResponse
	6,  // [6:11] is the sub-list for method output_type
	1,  // [1:6] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_kvstore_interface_grpc_kvstore_proto_init() }
func file_pkg_kvstore_interface_grpc_kvstore_proto_init() {
	if File_pkg_kvstore_interface_grpc_kvstore_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_kvstore_interface_grpc_kvstore_proto_rawDesc), len(file_pkg_kvstore_interface_grpc_kvstore_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_kvstore_interface_grpc_kvstore_proto_goTypes,
		DependencyIndexes: file_pkg_kvstore_interface_grpc_kvstore_proto_depIdxs,
		MessageInfos:      file_pkg_kvstore_interface_grpc_kvstore_proto_msgTypes,
	}.Build()
	File_pkg_kvstore_interface_grpc_kvstore_proto = out.File
	file_pkg_kvstore_interface_grpc_kvstore_proto_goTypes = nil
	file_pkg_kvstore_interface_grpc_kvstore_proto_depIdxs = nil
}
